
class Model_Config:
    IMAGE_SIZE = (256,256)
    def __init__(self):
        pass

COLOR_LABEL = {
    'f54337': 'Pharmacy',
    'ea1e63': 'Chinese Pharmacy',
    '009788': 'Lobby',
    '673ab7': 'Emergency Department',
    '3f51b5': 'Infectious Disease Clinic',
    '2196f3': 'Outpatient Treatment',
    '03a9f5': 'Radiology',
    '00bcd5':'Pediatric Unit',
    'cfd8dd': 'Corridor',
    '757575': 'Stairs',
    'bdbdbd': 'Elevator',
    '9e9e9e': 'Escalator',
    '4cb050': 'Landscape Space',
    'ffeb3c': 'Wall',
    '795547': 'Door',
    '9c28b1': 'Outside',
    '8cc34b': 'Endoscopy Center',
    'cddc39': 'Testing Center',
    'fec107': 'Gastroenterology',
    'ff9801': 'Endocrinology',
    'fe5721': 'Respiratory Medicine',
    'aaee5b': 'Cardiovascular Medicine',
    '607d8b': 'Health Examination Department',
    'efc74e': 'Ophthalmology',
    'feba57': 'Chinese medicine',
    'fb8561': 'Oral Medicine',
    'c6fe83': 'Otorhinolaryngology',
    '7ca5b9': 'Ultrasound Department',
    'ad850a': 'Functional Inspection Department',
    'ffd495': 'Rehabilitation Medicine Department',
    'fa918b': 'Orthopedics',
    'ff80ab': 'Nephrology',
    '21fae7': 'Physical Medicine and Rehabilitation',
    '8d4eff': 'Hematology',
    '526cff': 'Dermatology',
    'e23aff': 'Gynecology',
    '648b38': 'Obstetrics',
    'eeff3d': 'Outpatient Surgery'}